
spring.datasource.url=jdbc:h2:file:~/Documents/Coding/demo/src/main/resources/profile
spring.h2.console.enabled = true
spring.h2.console.settings.web-allow-others = true
spring.sql.init.mode= never
# spring.servlet.multipart.enabled=true
# spring.jpa.hibernate.ddl-auto=update